version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pulmo-rehab-db-dev
    environment:
      # Variables postgres container uses (reads from .env via compose)
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pulmo-rehab-network
    ports:
      - "5433:5432" # Map host 5433 to container 5432
    restart: always
    healthcheck:
      test: [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost", # Use $$ for escaping
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: pulmo-rehab-app-dev
    # Build context defined in override or here if no override used
    build:
      context: .
      dockerfile: Dockerfile
      target: production # Default target if no override is used (dev uses override file)
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    # --- Use env_file exclusively for database credentials ---
    env_file:
      - .env
    # --- Remove explicit database vars from environment block ---
    # Let env_file handle DATABASE_NAME, DATABASE_HOST, DATABASE_USER, DATABASE_PASSWORD
    environment:
      RAILS_ENV: ${RAILS_ENV:-development} # Still set RAILS_ENV default
      RAILS_LOG_TO_STDOUT: true
      # Remove other explicit DB vars:
      # DATABASE_USERNAME: ${POSTGRES_USER} # REMOVED
    volumes:
      # Base volumes (can be overridden/added to by override file)
      - bundle_cache:/usr/local/bundle
      # Note: Code volume moved to override file for clarity
    networks:
      - pulmo-rehab-network
    restart: unless-stopped
    # CMD is inherited from Dockerfile unless overridden

volumes:
  postgres_data:
  bundle_cache:

networks:
  pulmo-rehab-network:
    driver: bridge
