# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Ensure NO 'socket:' line here for Docker connection

development:
  <<: *default
  # Use consistent ENV variables loaded via compose's env_file or environment block
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %> # Changed from DATABASE_USERNAME to DATABASE_USER
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %> # Optional

test:
  <<: *default
  database: pulmo_rehab_test # Consider using ENV vars for test DB too
  # Set HOST/USER/PASSWORD via ENV for CI if needed, e.g., using defaults:
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  # Use consistent ENV variables
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  # port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %> # Optional